name: pide_claudia
description: "App de pedidos para tienda de comidas Platos de Claudia."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  

  # Sonidos
  audioplayers: ^6.5.1

  # Gráficas
  fl_chart: ^0.69.0

  # UI y utilidades
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  provider: ^6.1.2
  
  # HTTP
  http: ^1.2.2
  
  # Firebase - VERSIONES COMPATIBLES Y RECIENTES
  firebase_core: 3.6.0
  firebase_auth: 5.3.1
  cloud_firestore: 5.4.4
  firebase_storage: 12.3.2

  # Otros
  intl: 0.19.0
  url_launcher: 6.3.1
  image_picker: 1.1.2
  file_picker: 8.1.2

  # Navegación
  go_router: ^14.8.1

  # Animaciones
  animations: ^2.0.11

  # Estado avanzado
  flutter_riverpod: ^2.6.1
  flame: ^1.32.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  
  # Testing con Firebase - COMPATIBLE
  firebase_auth_mocks: 0.14.0
  fake_cloud_firestore: 3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/sounds/new-notification-09-352705.mp3

# Icono de la app
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"

# Splash screen
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.jpg
  android: true
  ios: true